# Generated by Django 6.0.2 on 2026-02-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_section'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('school_class', 'class_section'), name='unique_section_per_class'),
        ),
    ]
