# Generated by Django 6.0.2 on 2026-03-02 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_section_class_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.class'),
        ),
    ]
