# Generated by Django 6.0.2 on 2026-03-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_section_school_class'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='class',
            constraint=models.UniqueConstraint(fields=('grade', 'academic_year'), name='unique_class_per_academic_year'),
        ),
    ]
